language: node_js
node_js:
- 12.6.0
script:
- npm run lint
- npm run test
deploy:
  provider: npm
  email: zinovik@gmail.com
  on:
    repo: zinovik/node-audio-collection
    branch: master
  skip_cleanup: true
  api_key:
    secure: NIMnIZuIwZ4EaOn94z03QPs5X5Q2ZPPRpEP3LTuKNgotMKaGDEMBSZbP7ManT+0dGH8mnDhipMYOMwaCtjXlej2LBOow/dRtApY7YuFQ/JogjVga/ClpfUKahbzivniOTZgYro1FAJSBPSHQIQNU/jNXLd5FfGPbxgbUNGx2+5NAoyf7ZRZpRJSdXeacseAh7OFDsGEJtco0xBjrip0LH3YzKN7BU2riFZ/NIubxbGvmvK6WYUqtQAE8bqhW0J49N1pIpD5DlvNGIhV0H6Zrx6F7ikXuZ5tsZzlq8OKGxmC1C7sJfhocW4N1Pv7YkFY38mEXLBMDNUOjZ75r4RJqh6WCabldq699wzd/HxF8pQ9WA3x7AoE1nJjhaIXoZJ7A4yOH8ycfyAoRMqochPS1tw0TT6PWWFb4XbWyYCASHAqnTcahSv8zOx8n17adsXilkw3K6b/5StCeUDo0d2CXuQQytDwVRe09Mv0YETtBogwDby/Gi+WyVvvW4lkPdSeUtBhCuGBo3PV+iFBPTqmvtRSY8G9u43Dx5ituCj3SS+w6gnEwmG94Lriqr1QgUNukQChsAvUKw3biMFCPUAwJlrf6ryko8Pakx6CzwHME1O0glslQEdS4AV635Bu5jBsEUvjf9jaoRp7KTcwHmIMEbOV3T0zIMkYsiYGxCqqyYQ4=
