language: node_js
node_js:
- 12.6.0
script:
- npm run lint
- npm run test
deploy:
  provider: npm
  email: zinovik@gmail.com
  on:
    repo: zinovik/node-audio-collection
    branch: master
  skip_cleanup: true
  api_key:
    secure: XM7nZatZSsmiuaUDi6tE4/Vk+wiUilKn9WLemwJZxTLK14ctgBE70koGBm+NVpWTro6LgagKIpjUqwema7yVU+7JL3ltj7lc05BfxlS4iihVbcFVD7FMATJr1u02YxfOdJvv1vXSEcqzcA37oOCwLF8S9MmXewiZQe+gBDoDQ9u/9VKo7pr1srWTbqXFkJj6nOtaul+e5S6042cfr9PRFqbFIjSQslgz4iA73vTPs0Xu6tH+8XBRBShAIDPk3w/nsFSoxAyVpdEBtOnDkWz3x3TUrxt6SHXkIelXhRPb/ALeJNqFGh3y9gsmbQbUdJT8/h3iQek89wEqpNhTtNd71+cBOhV4JX7Kg6aDvbeS5EmC2/WMU10eYOdffrvojQ0pL3NcJTUbM0ScqKooXV6lf8mRt+eAuQbhh1ur1DAzhRLZOOo66QL9ou59yVMWqg5MTYQTe3d2Sh8mBVuqSAGGviC5AdOY0xTjJ7IeWx7Gcw9ZZgIBjOtro2W+btIR+CzJ5Mb29DJcgQgibVYDx/vYOpCLFJYhm7SD92kQAwVsxTRcAeZxdwNdrRjBmIMvOb31TNJoHGua6agjNLzSKHxznN4snzkVZ4XpL+xnK4AAqivqRBOSIkHkGG2CSTvGU7Rt+xOwFqL1sg3fYBLP2EaSNwS1D/PtxxslQH2WPWjJAkg=
